# Generated by Django 5.1.6 on 2025-02-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackflow', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='defaultUserImg.jpg', null=True, upload_to=''),
        ),
    ]
